config/routes.rb
Rails.application.routes.draw do

  get 'contact_card/index'

  get 'client_card/index'

  devise_for :users

  root 'static#index'
  get 'bills' => 'static#bills'
  get 'clients' => 'static#clients'
  get 'contacts' => 'static#contacts'
  get 'purchase' => 'static#purchase'
  get 'history' => 'static#history'
  get '/clients(/page/:page)' => 'static#clients', :as => :static, :page => 1

  get 'client/:id' => 'client_card#index'
  get 'clients/add' => 'static#new_client'
  post 'clients/add' => 'static#create_client'

  get 'contact/:id' => 'contact_card#index'
  get 'contacts/add' => 'static#new_contact'
  # Client Card action

  # Contact Card actions


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  self.table_name = 'address'
end

app/models/bill.rb
class Bill < ApplicationRecord
  self.table_name = 'bills'
  has_one :client, class_name: 'Client', foreign_key: 'ClientId', primary_key: 'BillContragentId'
  has_one :bill_status, class_name: 'BillStatus', foreign_key: 'BillStatusId', primary_key: 'BillStatus'

end

app/models/bill_status.rb
class BillStatus < ApplicationRecord
  self.table_name = 'billstatus'

end

app/models/call.rb
class Call < ApplicationRecord
  has_one :call_status, class_name: 'CallStatus', primary_key: 'CallType',foreign_key: 'callStatusId'
  has_one :contact, class_name: 'Contact', primary_key: 'CallContact', foreign_key: 'IDContact'
  has_one :client, class_name: 'Client', primary_key: 'CallContragent', foreign_key: 'ClientId'




end

app/models/call_status.rb
class CallStatus < ApplicationRecord
  self.table_name = 'call_status'
end

app/models/client.rb
class Client < ApplicationRecord
  self.table_name = 'clients'
  self.primary_key = 'ClientId'
  paginates_per 100
  has_many :workplaces, :class_name => 'Workplace', primary_key: 'ClientId', foreign_key: 'wpClientId'
  has_one :client_property, :class_name => 'ClientProperty', primary_key: 'ClientProperty', foreign_key: 'ClientPropertyId'
  has_one :client_type, class_name: 'ClientType', primary_key: 'ClientType', foreign_key: 'ClientTypeId'
  has_one :client_vid, class_name: 'ClientVid', primary_key: 'ClientVid', foreign_key: 'ClientVidId'

  has_many :contacts, class_name: 'Contact', primary_key: 'ClientId', through: :workplaces

  has_many :telephones,-> { where stat: 2 }, class_name: 'Telephone', primary_key: 'ClientId', foreign_key: 'IDEmpl'
  has_many :emails,-> { where stat: 2 }, class_name: 'Email', primary_key: 'ClientId', foreign_key: 'IDEmplEmail'
  has_many :links,-> { where stat: 2 }, class_name: 'Link', primary_key: 'ClientId', foreign_key: 'IDEmplLink'

  has_many :addresses, class_name: 'Address', primary_key: 'ClientId', foreign_key: 'client_address'

  has_many :bills,->{where arel_table[:BillStatus].not_eq(0)}, :class_name => 'Bill', :foreign_key => 'BillContragentId', primary_key: 'ClientId'
  has_many :purchases, class_name: 'Purchase', primary_key: 'ClientId', foreign_key: 'purchaseContragent'

  has_many :calls, class_name: 'Call', primary_key: 'ClientId',foreign_key: 'CallContragent', through: :contacts

end

app/models/client_property.rb
class ClientProperty < ApplicationRecord
  self.table_name = 'client_property'
end

app/models/client_type.rb
class ClientType < ApplicationRecord
  self.table_name = 'client_type'
end

app/models/client_vid.rb
class ClientVid < ApplicationRecord
  self.table_name = 'client_vid'
end

app/models/contact.rb
class Contact < ApplicationRecord
  self.table_name = 'contacts'
  self.primary_key = 'IDContact'
  has_many :workplaces, :class_name => 'Workplace', primary_key: 'IDContact', foreign_key: 'wpContactId'

  has_many :telephones,->{where stat: 1}, class_name: 'Telephone', primary_key: 'IDContact', foreign_key: 'IDEmpl'
  has_many :emails,-> { where stat: 1 }, class_name: 'Email', primary_key: 'IDContact', foreign_key: 'IDEmplEmail'
  has_many :links,-> { where stat: 1 }, class_name: 'Link', primary_key: 'IDContact', foreign_key: 'IDEmplLink'

  has_one :client, class_name: 'Client',  foreign_key: 'ClientId',  through: :workplaces
  has_many :calls, class_name: 'Call', primary_key: 'IDContact',foreign_key: 'CallContact'
end

app/models/email.rb
class Email < ApplicationRecord
  self.table_name = 'email'
end

app/models/link.rb
class Link < ApplicationRecord
  self.table_name = 'link'
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  self.table_name = 'purchase'
  has_one :client, class_name: 'Client', foreign_key: 'ClientId', primary_key: 'purchaseContragent'
  has_one :purchase_status, class_name: 'PurchaseStatus', foreign_key: 'psId', primary_key: 'purchaseStatus'
end

app/models/purchase_status.rb
class PurchaseStatus < ApplicationRecord
  self.table_name = 'purchase_status'
end

app/models/sex.rb
class Sex < ApplicationRecord
  self.table_name = 'sex'
end

app/models/telephone.rb
class Telephone < ApplicationRecord
  self.table_name = 'telephone'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            } # etc.


end

app/models/workplace.rb
class Workplace < ApplicationRecord
  self.table_name = 'workplace'
  belongs_to :client
  belongs_to :contact, foreign_key: 'wpContactID'

end

app/helpers/bill_helper.rb
module BillHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=t :project_name %> | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'bootstrap' %>
    <%= stylesheet_link_tag 'dashboard' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" %>
    <%= javascript_include_tag 'bootstrap' %>
  </head>

  <body>

  <div class="container">
    <% if user_signed_in? %>
        <%= render template: 'layouts/menu' %>
    <% else %>

        <% end%>

  <p id="notice"><%= notice %></p>
  <p id="notice"><%= alert %></p>
    <%= yield %>
    <div class="footer">
      <p>© ООО ЗСС Маяк 2016</p>
    </div>
  </div>

  </body>
</html>

app/views/layouts/menu.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ООО ЗСС Маяк</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= active_class(root_path) %>">
          <%= link_to "Главня", root_path %>
        </li>
        <li class="<%= active_class(clients_path) %>">
          <%= link_to "Клиенты", clients_path %>
        </li>
        <li class="<%= active_class(contacts_path) %>">
          <%= link_to "Контакты", contacts_path %>
        </li>
        <li class="<%= active_class(bills_path) %>">
          <%= link_to "Счета", bills_path %>
        </li>
        <li class="<%= active_class(purchase_path) %>">
          <%= link_to "Эл. Торги", purchase_path %>
        </li>
        <li class="<%= active_class(history_path) %>">
          <%= link_to "История", history_path %>
        </li>

        <!--
        <li {!!(Request::is('/')) ? ' class="active"' : '' !!}><a href="/">Главная</a></li>
        <li {!!(Request::is('clients')) ? ' class="active"' : (Request::is('client/*') ? ' class="active"' : '' )  !!}><a href="/clients">Контрагенты</a></li>
        <li {!!(Request::is('contacts')) ? ' class="active"' :(Request::is('contact/*') ? ' class="active"' : '' ) !!}><a href="/contacts">Контакты</a></li>
        <li {!!(Request::is('bills')) ? ' class="active"' : '' !!}><a href="/bills">Счета</a></li>
        <li {!!(Request::is('purchase')) ? ' class="active"' : '' !!}><a href="/purchase">Эл. торги</a></li>
        <li {!!(Request::is('calls')) ? ' class="active"' : '' !!}><a href="/calls">История</a></li>
        <li {!!(Request::is('mail')) ? ' class="active"' : '' !!}><a href="/mail">Mail</a></li>
        !-->

      </ul>
      <div class="col-sm-2 col-md-2">
        <form class="navbar-form" role="search" method="post" action="/search">
          <div class="input-group">
            <input type="text" class="form-control   input-ssx"  placeholder="Поиск" name="q">

          </div>
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
        </form>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Мои данные</a></li>
            <li><a href="#">История</a></li>

            <li class="divider"></li>
            <li class="dropdown-header"><%= current_user.username %></li>

            <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>


      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>